name: Npm publish
# permissions:
#   contents: write
on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out git repository
        uses: actions/checkout@v3.0.0

      - name: Install Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16

      - name: publish
        run: |
          git config --global user.name "houdunwang"
          git config --global user.email "2300071698@qq.com"
          npm version ${{ github.event.release.tag_name }}
          npm publish
